### ISSUE TITLE
Support for dollar format rounded

### ISSUE THREAD

**Issue by xergiodf** [mohammadrezaeicode/mr-excel-repo#2]
Hello 👋 

Is it possible to include a "rounded` dollar format? I need to export an Excel file with dollar-formatted cells without any cents. I've gone through documentation and codes for the format and I couldn't find anything.

I could use the `num_sep` format, but I'll be missing the dollar sign and the cell will be formatted as a number.

I tried forking the project and I have a [draft PR](https://github.com/mohammadrezaeicode/mr-excel-repo/pull/1/files) with what I think is a good start for implementing this, but I couldn't compile the project. Are there any contribution guidelines?

I really appreciate any help you can provide.

**Comment by mohammadrezaeicode** [comment]
Thank you for your contribution. The PR has been merged, and the new version has been released
